FROM python:3.12.7-slim

WORKDIR /app
COPY . /app

RUN apt update -y && \
    apt install -y awscli && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*



RUN pip install -r requirements.txt
CMD ["python3","application.py"]